sudo: false
language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "nightly"
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
  allow_failures:
    - python: "nightly"
install:
  - pip install -r requirements.txt
script: 
  - invoke test
