sudo: false
language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "nightly"
install:
  - pip install -r requirements.txt
script: 
  - invoke test
matrix:
  allow_failures:
    - python: "nightly"